sudo: true
language: java
jdk: openjdk8
before_install:
    - sudo dpkg --add-architecture i386
    - sudo apt-get update
addons:
  apt:
    packages:
    - openjdk-8-jdk:i386
after_install:
    - sudo update-java-alternatives --set java-1.8.0-openjdk-i386