version: build {build} {branch}

os: Visual Studio 2017

platform: x86
 
clone_depth: 50

install:
  - cmd: SET PATH=C:\Progra~2\Java\jdk1.8.0\bin;%PATH%
  - cmd: SET JAVA_HOME=C:\Progra~2\Java\jdk1.8.0
  - cmd: echo %PATH%
  - cmd: echo %JAVA_HOME%
  - cmd: java -version

build:
  verbosity: detailed

build_script:
  - gradlew.bat clean fatjar --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

notifications:
  - provider: Email
    to:
      - jabbo16@gmail.com
    on_build_success: false
    on_build_status_changed: true
