version: build {build}

branches:
  only:
  - master

image: 
  - Visual Studio 2017

build:
  verbosity: detailed

build_script:
  - gradlew.bat clean fatjar --info

cache:
  - '%USERPROFILE%\.gradle'

artifacts:
  - path: 'build\libs\*.*'
    name: Ecgberht
    
notifications:
  - provider: Email
    to:
      - jabbo16@gmail.com
    on_build_success: false
    on_build_status_changed: true
